### ISSUE TITLE
Suggestion regarding file access logs

### ISSUE THREAD

**Issue by mgeeky** [tehsyntx/loffice#7]
Since file access logs are quite frequently generated during Office program initialization and termination, they are making the general program's output a bit unreadable.
Talking about those lines:

```
    if access is not '' and '\\\\' not in filename[:2]: # Exclude PIPE and WMIDataDevice
        if writes_only and 'W' in access:
            logger.info('Opened file handle (access: %s):\n\t%s\n' % (access, filename))
        elif not writes_only:
            logger.info('Opened file handle (access: %s):\n\t%s\n' % (access, filename))
```

I would suggest making from `logger.info` invocations into `logger.debug` and let the user choose by using `-v` parameter whether he wants those file access events to be displayed or not. :)

**Comment by tehsyntx** [comment]
This have been somewhat addressed in the current dev-branch as the logging have been revised into file rather than stdout plus some other things.
